# Copyright 2026 k8s-gpu-mcp-server contributors
# SPDX-License-Identifier: Apache-2.0
#
# Agent RBAC - Read-Only Mode (Default)
# Minimal permissions for GPU monitoring and diagnostics.
#
# Usage:
#   kubectl apply -f deployment/rbac/agent-rbac-readonly.yaml
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-gpu-mcp-server-agent-readonly
  labels:
    app.kubernetes.io/name: k8s-gpu-mcp-server
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: k8s-gpu-mcp-server
rules:
  # Node information for describe_gpu_node tool
  # Required to query GPU node labels, taints, capacity, and conditions
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  # Pod information for get_pod_gpu_allocation tool
  # Required to list pods with GPU allocations across all namespaces
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  # EXCLUDED: pods/exec - agent doesn't exec into other pods
  # EXCLUDED: secrets - agent never needs secrets
  # EXCLUDED: configmaps - agent reads config from flags/env only
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-gpu-mcp-server-agent-readonly
  labels:
    app.kubernetes.io/name: k8s-gpu-mcp-server
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: k8s-gpu-mcp-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-gpu-mcp-server-agent-readonly
subjects:
  - kind: ServiceAccount
    name: k8s-gpu-mcp-server
    namespace: gpu-diagnostics
