# golangci-lint configuration for k8s-mcp-agent
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - typecheck     # Type-check Go code
    - unused        # Check for unused code
    
    # Additional linters
    - gofmt         # Check code formatting
    - goimports     # Check import order
    - gocritic      # Comprehensive Go source code linter
    - revive        # Fast, configurable, extensible linter
    - misspell      # Spell checker
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Detect unused function parameters
    - whitespace    # Detect leading/trailing whitespace
    - gocyclo       # Compute cyclomatic complexity
    - dupl          # Code clone detection
    - godox         # Detect FIXME, TODO, and other comments
    - errname       # Check error naming conventions
    - errorlint     # Find code that will cause problems with Go 1.13 error wrapping
    - goconst       # Find repeated strings that could be constants
    - gosec         # Security checker
    - nolintlint    # Validate //nolint directives
    - stylecheck    # Replacement for golint

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - shadow  # Can be too strict for nested contexts
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/ArangoGutierrez/k8s-mcp-agent
  
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - whyNoLint  # We use nolintlint for this
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  godox:
    keywords:
      - FIXME
      - BUG
      - HACK
  
  misspell:
    locale: US
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gosec:
    excludes:
      - G204  # Subprocess launched with variable (needed for kubectl debug)
  
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]  # Allow non-standard package names
  
  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
    
    # Exclude internal packages from export comments
    - path: internal/
      linters:
        - revive
      text: "exported:"
    
    # Exclude cmd/agent/main.go from certain checks
    - path: cmd/agent/main\.go
      linters:
        - errcheck
      text: "Error return value"
    
    # Allow print statements in main packages
    - path: cmd/
      linters:
        - forbidigo
  
  # Independently from option `exclude` we use default exclude patterns
  exclude-use-default: false
  
  # Show all issues from a linter
  new: false
  
  # Fix found issues (if supported by the linter)
  fix: false

