name: Bug Report
description: Report a bug or unexpected behavior in k8s-mcp-agent
title: "[Bug]: "
labels: ["kind/bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thank you for taking the time to report a bug. Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Launch agent with: kubectl debug node/...
        2. Call MCP tool: get_gpu_inventory
        3. Observe error: ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Agent should return GPU inventory as JSON...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages, logs, or stack traces.
      placeholder: |
        Error: failed to initialize NVML: ...
        Logs: {"level":"error","msg":"..."}
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Component Area
      description: Which part of the system is affected?
      options:
        - MCP Protocol/Transport
        - NVML Hardware Binding
        - Kubernetes Integration
        - Tool Implementation
        - Build/Container
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment.
      placeholder: |
        - Agent Version: v0.1.0
        - Kubernetes Version: 1.28
        - Node OS: Ubuntu 22.04
        - NVIDIA Driver: 535.129.03
        - GPU Model: A100
        - Deployment Method: kubectl debug / container
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste relevant logs (from stderr). Use ``` code blocks.
      placeholder: |
        ```json
        {"level":"error","component":"nvml","msg":"initialization failed"}
        ```
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, related issues, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I searched existing issues to avoid duplicates
          required: true
        - label: I included relevant logs and error messages
          required: true
        - label: This bug is reproducible on the latest version
          required: false

