name: Feature Request
description: Suggest a new feature or enhancement for k8s-gpu-mcp-server
title: "[Feature]: "
labels: ["kind/feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Thank you for suggesting a new feature! Please provide details to help us understand and evaluate the proposal.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature.
      placeholder: Add support for monitoring GPU memory bandwidth...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the user pain point?
      placeholder: |
        As an SRE debugging training performance issues, I need to see 
        real-time memory bandwidth to identify bottlenecks...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Add a new MCP tool `get_gpu_bandwidth` that returns:
        - Current memory bandwidth utilization
        - PCIe bandwidth metrics
        - NVLink bandwidth per GPU pair
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Are there other ways to solve this problem?
      placeholder: Could use nvidia-smi, but requires shell access...

  - type: dropdown
    id: area
    attributes:
      label: Component Area
      description: Which part of the system would this affect?
      options:
        - MCP Tool (New)
        - NVML Binding Extension
        - Kubernetes Integration
        - CLI/Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: milestone
    attributes:
      label: Suggested Milestone
      description: Which milestone should this target?
      options:
        - M1 - Foundation & API
        - M2 - Hardware Introspection
        - M3 - Ephemeral Tunnel
        - M4 - Safety & Release
        - Future (Post-M4)
        - Unsure
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - P0 - Blocker (critical for release)
        - P1 - High (should have)
        - P2 - Medium (nice to have)
        - P3 - Low (future consideration)
    validations:
      required: true

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any implementation notes, API changes, or dependencies?
      placeholder: |
        - Requires NVML 12.0+ for bandwidth APIs
        - May need operator mode for some metrics
        - Should cache results for 1s to avoid overhead

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Links, references, screenshots, or other relevant information.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I searched existing issues/PRs for similar requests
          required: true
        - label: This feature aligns with the project's ephemeral/read-only design
          required: true
        - label: I am willing to contribute to implementation
          required: false

